let filterCarteira=false;
function toggleCarteiraFilter(){filterCarteira=!filterCarteira;const btn=document.getElementById('btnCarteira');btn.classList.toggle('cart-active',filterCarteira);btn.textContent=filterCarteira?'💼 Carteira ✓':'💼 Carteira';applyFilters();}
const segs=[...new Set([...document.querySelectorAll('#tableBody tr')].map(r=>r.dataset.segmento).filter(Boolean))].sort();const segDiv=document.getElementById('segFilter');let activeSeg='';
segs.forEach(s=>{const btn=document.createElement('button');btn.className='filter-btn';btn.dataset.seg=s;btn.textContent=s;btn.style.cssText='font-size:10px;padding:4px 8px;';btn.addEventListener('click',()=>{segDiv.querySelectorAll('.filter-btn').forEach(b=>b.classList.remove('active'));if(activeSeg===s){activeSeg='';applyFilters();}else{btn.classList.add('active');activeSeg=s;applyFilters();}});segDiv.appendChild(btn);});
let sortCol=-1,sortAsc=true;
document.querySelectorAll('th[data-col]').forEach(th=>{th.addEventListener('click',()=>{const col=parseInt(th.dataset.col);if(col===0||col===22)return;if(sortCol===col)sortAsc=!sortAsc;else{sortCol=col;sortAsc=true;}document.querySelectorAll('th[data-col]').forEach(h=>h.classList.remove('sorted-asc','sorted-desc'));th.classList.add(sortAsc?'sorted-asc':'sorted-desc');const tbody=document.getElementById('tableBody');Array.from(tbody.querySelectorAll('tr')).sort((a,b)=>{const aV=a.cells[col]?.textContent.trim()||'',bV=b.cells[col]?.textContent.trim()||'',aN=parseFloat(aV.replace(/[^0-9.-]/g,'')),bN=parseFloat(bV.replace(/[^0-9.-]/g,''));if(!isNaN(aN)&&!isNaN(bN))return sortAsc?aN-bN:bN-aN;return sortAsc?aV.localeCompare(bV,'pt-BR'):bV.localeCompare(aV,'pt-BR');}).forEach(r=>tbody.appendChild(r));});});
document.getElementById('searchInput').addEventListener('input',applyFilters);
let activeFilter='all';
document.querySelectorAll('.filter-btn[data-filter]').forEach(btn=>{btn.addEventListener('click',()=>{document.querySelectorAll('.filter-btn[data-filter]').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;applyFilters();});});
function applyFilters(){const s=document.getElementById('searchInput').value.toLowerCase();let cC=0,cA=0,cT=0,cCart=0;document.querySelectorAll('#tableBody tr').forEach(row=>{const emp=(row.dataset.empresa||'').toLowerCase(),verd=row.dataset.veredicto||'',seg=row.dataset.segmento||'',inCart=row.dataset.carteira==='true';const ok=(s===''||emp.includes(s))&&(activeFilter==='all'||verd===activeFilter)&&(activeSeg===''||seg===activeSeg)&&(!filterCarteira||inCart);row.classList.toggle('hidden',!ok);if(ok){if(verd==='compra')cC++;if(verd==='aguardar')cA++;if(inCart)cCart++;cT++;}});document.getElementById('cnt-compra').textContent=cC;document.getElementById('cnt-aguardar').textContent=cA;document.getElementById('cnt-carteira').textContent=cCart;document.getElementById('cnt-total').textContent=cT;}
// Fetch individual rápido — só corsproxy.io + Yahoo v8/chart (sem allorigins que trava 10s)
